services:
  db:
    image: postgis/postgis:15-3.4
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    ports: ["8080:8080"]
    depends_on: [db]
